const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

module.exports = async function ({ app, win, dialog, snapshot, runAction, openFile, setConnection, connectionFile, protection }) {
  const root = path.resolve('work/desktop-test');
  const errors = [], checks = [];
  win.webContents.on('console-message', details => { if (details.level === 'error') errors.push(details.message); });
  win.webContents.on('preload-error', (_event, _file, error) => errors.push(error.message));
  const js = code => win.webContents.executeJavaScript(code, true);
  const waitFor = async (code, label) => {
    const deadline = Date.now() + 8000;
    while (Date.now() < deadline) { if (await js(code)) return; await new Promise(resolve => setTimeout(resolve, 50)); }
    throw new Error(`Timed out: ${label}`);
  };
  const check = label => { checks.push(label); console.log(`PASS ${label}`); };
  const edit = async text => {
    await new Promise(resolve => setTimeout(resolve, 600));
    win.focus(); win.webContents.focus();
    await js("document.querySelector('.cm-content').focus()");
    if (snapshot().text.length) {
      win.webContents.send('editor:command', 'select-all');
      await waitFor("window.getSelection().toString().length > 0", 'select-all command');
    }
    await win.webContents.insertText(text);
    await waitFor(`window.beat.current().then(doc => doc.text.length === ${text.length})`, 'editor insertion');
    assert.equal(snapshot().text, text);
    await waitFor("document.getElementById('save-state').textContent === 'Unsaved changes'", 'document sync');
  };
  let nextSave = path.join(root, 'roundtrip.fountain');
  let nextOpen;
  let answer = 2;
  dialog.showSaveDialog = async () => nextSave ? ({ canceled: false, filePath: nextSave }) : ({ canceled: true });
  dialog.showOpenDialog = async () => nextOpen ? ({ canceled: false, filePaths: [nextOpen] }) : ({ canceled: true, filePaths: [] });
  dialog.showMessageBox = async (_window, options) => {
    if (options.type === 'error') { errors.push(options.detail ?? options.message); return { response: 0 }; }
    return { response: answer };
  };
  try {
    await fs.mkdir(root, { recursive: true });
    win.show(); win.focus(); win.webContents.focus();
    await waitFor("document.querySelectorAll('.outline-item.scene').length === 2", 'initial outline');
    assert.equal(await js("typeof window.require"), 'undefined');
    assert.equal(await js("typeof window.beat.action"), 'function');
    check('real Electron window loads; isolated preload and two-scene outline');
    await js("document.body.classList.remove('light'); document.getElementById('theme').textContent='Light'; document.getElementById('theme').click(); document.getElementById('focus').click()");
    assert.equal(await js("document.body.classList.contains('light') && document.body.classList.contains('focus-mode')"), true);
    await js("document.getElementById('theme').click(); document.getElementById('focus').click()");
    check('theme and focus controls');
    await js("document.querySelectorAll('.outline-item.scene')[1].click()");
    assert.match(await js("document.getElementById('cursor').textContent"), /Scene/);
    check('outline navigation selects the scene');

    await edit('INT. TEST ROOM - DAY\n\nA first line.\n\nTESTER\nIt works.\n\nEXT. TEST ROAD - NIGHT\n\nA second scene.\n');
    await waitFor("document.querySelectorAll('.outline-item.scene').length === 2 && document.querySelector('.outline-item.scene').textContent.includes('TEST ROOM')", 'live outline');
    assert.equal(snapshot().dirty, true);
    assert.equal(await js("document.querySelectorAll('.element-character').length"), 1);
    assert.equal(await js("document.querySelectorAll('.element-dialogue').length"), 1);
    check('keyboard editing, live Fountain formatting and host dirty state');

    const filter = await js("(() => {const input=document.getElementById('outline-filter');input.value='ROAD';input.dispatchEvent(new Event('input'));return document.querySelectorAll('.outline-item.scene').length;})()");
    assert.equal(filter, 1);
    await js("document.getElementById('outline-filter').value='';document.getElementById('outline-filter').dispatchEvent(new Event('input'))");
    await runAction('save');
    assert.equal(await fs.readFile(nextSave, 'utf8'), snapshot().text);
    assert.equal(snapshot().dirty, false);
    check('scene filtering and native-host file save');

    const textBefore = snapshot().text;
    await edit('INT. CHANGED - DAY\n\nChanged.\n');
    answer = 2;
    await runAction('new');
    assert.match(snapshot().text, /CHANGED/);
    nextSave = null;
    await runAction('save-as');
    assert.match(snapshot().text, /CHANGED/);
    check('cancelled discard and cancelled Save As both preserve edits');
    win.webContents.send('editor:command', 'undo');
    await waitFor("document.querySelector('.cm-content').textContent.includes('TEST ROOM')", 'undo');
    win.webContents.send('editor:command', 'redo');
    await waitFor("document.querySelector('.cm-content').textContent.includes('CHANGED')", 'redo');
    check('undo and redo restore the correct document text');
    nextSave = path.join(root, 'roundtrip.fountain');
    await fs.writeFile(nextSave, 'An outside editor wrote this.');
    assert.equal(await runAction('save'), false);
    assert.equal(await fs.readFile(nextSave, 'utf8'), 'An outside editor wrote this.');
    assert.match(errors.pop(), /changed outside/);
    check('external-file changes cannot be silently overwritten');
    answer = 1; await runAction('new');
    await waitFor("document.querySelector('.cm-content').textContent === ''", 'new document');
    assert.equal(snapshot().text, '');
    win.webContents.send('editor:command', 'undo');
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.equal(snapshot().text, '');
    check('new document clears history; undo cannot leak the previous file');

    const protectedFile = path.join(root, 'metadata.fountain');
    const source = '\uFEFFINT. ORIGINAL - DAY\r\n\r\n😀 Original.\r\n\r\n/** settings: {"Tags":[[1,2]],"custom":42} **/\r\n';
    await fs.writeFile(protectedFile, source);
    nextOpen = protectedFile; await runAction('open');
    await waitFor("!document.getElementById('metadata-banner').hidden", 'metadata banner');
    assert.equal(snapshot().readOnly, true);
    assert.equal(await js("document.querySelector('.cm-content').getAttribute('contenteditable')"), 'false');
    const rejected = await js("window.beat.current().then(doc=>window.beat.update(doc.id,'malicious overwrite',doc.revision+1))");
    assert.equal(rejected, false);
    nextSave = path.join(root, 'metadata-copy.fountain');
    await runAction('save-as');
    assert.equal(await fs.readFile(nextSave, 'utf8'), source);
    check('metadata documents resist renderer edits and save byte-for-byte');

    const protectedPath = snapshot().path;
    answer = 0; await runAction('editable-copy');
    await waitFor("document.getElementById('metadata-banner').hidden", 'editable copy');
    assert.equal(snapshot().readOnly, false);
    assert.equal(snapshot().path, null);
    nextSave = protectedPath;
    assert.equal(await runAction('save'), false);
    assert.match(errors.pop(), /different filename/);
    assert.equal(await fs.readFile(protectedPath, 'utf8'), source);
    nextSave = protectedFile;
    assert.equal(await runAction('save'), false);
    assert.match(errors.pop(), /different filename/);
    assert.equal(await fs.readFile(protectedFile, 'utf8'), source);
    nextSave = path.join(root, 'editable.fountain'); await runAction('save');
    assert.ok(!(await fs.readFile(nextSave, 'utf8')).includes('settings:'));
    check('editable copies omit metadata and cannot overwrite their source');

    const bad = path.join(root, 'bad-encoding.fountain');
    await fs.writeFile(bad, Buffer.from([0xff, 0xfe, 0x00, 0x00]));
    nextOpen = bad; const before = snapshot().id;
    assert.equal(await runAction('open'), false);
    assert.equal(snapshot().id, before);
    assert.match(errors.pop(), /encoded data|encoding/i);
    check('invalid UTF-8 cannot replace the active document');

    await openFile(path.resolve('../Sample files/Big-Fish.fountain'));
    await waitFor("document.querySelectorAll('.outline-item.scene').length > 100", 'real script');
    assert.equal(snapshot().readOnly,false);
    check('upstream Big Fish sample opens with over 100 navigable scenes');

    const automationFile = path.join(root, 'automation.fountain');
    const automationSource = 'INT. LAB - DAY\n\nAlice watches Alice.\n\nEXT. ROAD - NIGHT\n\nA quiet road.\n';
    await fs.writeFile(automationFile, automationSource); await openFile(automationFile);
    await waitFor("document.getElementById('filename').textContent==='automation.fountain'", 'automation test script');
    let connection = JSON.parse(await fs.readFile(connectionFile, 'utf8'));
    const remote = async (command, params = {}) => {
      const response = await fetch(`${connection.url}/v1/command`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${connection.token}` }, body: JSON.stringify({ command, params }) });
      const packet = await response.json();
      if (!response.ok) throw Object.assign(new Error(packet.error.message), { status: response.status, code: packet.error.code });
      return packet.result;
    };
    const guard = () => ({ documentId: snapshot().id, revision: snapshot().revision });
    const initial = await remote('get-document');
    assert.equal(initial.text, automationSource); assert.equal(initial.sceneCount, 2);
    const sceneOutline = await remote('get-outline'); assert.equal(sceneOutline.items.length, 2);
    assert.equal((await remote('find', { query: 'Alice' })).count, 2);
    check('live local API reads the current document, outline and literal matches');
    await remote('go-to-scene', { ...guard(), line: sceneOutline.items[1].line });
    assert.equal((await remote('get-selection')).selection.line, 5);
    const alice = automationSource.indexOf('Alice');
    await remote('select', { ...guard(), from: alice, to: alice + 5 });
    assert.equal((await remote('get-selection')).selection.text, 'Alice');
    check('Codex scene navigation and text selection reach the real editor');
    const originalGuard = guard();
    await assert.rejects(remote('edit', { ...guard(), edits: [{ from: alice, to: alice + 5, insert: 'Beatrice', expectedText: 'Wrong' }] }), error => error.code === 'CONFLICT');
    assert.equal(snapshot().text, automationSource);
    check('incorrect expected text is rejected without touching the screenplay');
    const matches = (await remote('find', { query: 'Alice' })).matches;
    await remote('edit', { ...guard(), edits: matches.map(match => ({ from: match.from, to: match.to, insert: 'Beatrice', expectedText: 'Alice' })) });
    const automatedText = automationSource.replaceAll('Alice', 'Beatrice');
    assert.equal(snapshot().text, automatedText); assert.equal(snapshot().dirty, true);
    await waitFor("document.getElementById('codex-connection').textContent.includes('edited')", 'Codex change label');
    check('multiple Codex edits apply together and remain visibly unsaved');
    await remote('select', { ...guard(), from: snapshot().text.length, to: snapshot().text.length });
    await win.webContents.insertText('\nA human edit.\n');
    await waitFor("document.querySelector('.cm-content').textContent.includes('A human edit.')", 'human edit after Codex');
    await remote('get-document');
    await remote('undo', guard()); assert.equal(snapshot().text, automatedText);
    await remote('undo', guard()); assert.equal(snapshot().text, automationSource);
    await remote('redo', guard()); assert.equal(snapshot().text, automatedText);
    check('human typing and the complete Codex edit undo separately and redo correctly');
    await assert.rejects(remote('edit', { ...originalGuard, edits: [{ from: 0, to: 0, insert: 'stale', expectedText: '' }] }), error => error.code === 'CONFLICT');
    check('stale revisions are rejected even after undo returns to earlier text');
    await assert.rejects(remote('replace', { ...guard(), find: 'Beatrice', replace: 'Alice', expectedOccurrences: 1 }), error => error.code === 'CONFLICT');
    await remote('replace', { ...guard(), find: 'Beatrice', replace: 'Alice', expectedOccurrences: 2 });
    assert.equal(snapshot().text, automationSource);
    check('literal replacement requires the reviewed occurrence count');
    await remote('save', guard()); assert.equal(snapshot().dirty, false); assert.equal(await fs.readFile(automationFile, 'utf8'), automationSource);
    check('Codex saves the named script through the existing protected file path');
    await openFile(protectedFile);
    await remote('get-document');
    await assert.rejects(remote('edit', { ...guard(), edits: [{ from: 0, to: 0, insert: 'forbidden', expectedText: '' }] }), error => error.code === 'READ_ONLY');
    assert.equal(await fs.readFile(protectedFile, 'utf8'), source);
    check('the local API cannot edit protected BEAT metadata documents');
    const oldToken = connection.token;
    await setConnection(false); await assert.rejects(fs.readFile(connectionFile), /ENOENT/);
    await waitFor("document.getElementById('codex-connection').textContent==='Codex paused'", 'paused connection');
    await setConnection(true); connection = JSON.parse(await fs.readFile(connectionFile, 'utf8'));
    assert.notEqual(connection.token, oldToken);
    assert.equal((await fetch(`${connection.url}/health`, { headers: { Authorization: `Bearer ${oldToken}` } })).status, 401);
    check('pausing removes discovery and resuming rotates the local credential');
    await openFile(automationFile);
    await remote('get-document');
    await js("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");
    await fs.writeFile(path.join(root, 'desktop-dark.png'), (await win.capturePage()).toPNG());
    await js("document.getElementById('theme').click()");
    await new Promise(resolve => setTimeout(resolve, 100));
    await fs.writeFile(path.join(root, 'desktop-light.png'), (await win.capturePage()).toPNG());
    const { createProtection } = require('../electron/protection.cjs');
    const { randomUUID } = require('node:crypto');
    const crashed = createProtection(protection.root);
    const recoverySource = path.join(root, 'recovery-original.fountain');
    const recoveryBytes = '\uFEFFINT. RECOVERY - DAY\r\n\r\nOriginal.\r\n';
    await fs.writeFile(recoverySource, recoveryBytes);
    const draft = { id: randomUUID(), filePath: recoverySource, model: { original: recoveryBytes }, text: 'INT. RECOVERY - DAY\n\nRecovered edit.\n', dirty: true, protectedPaths: new Set() };
    crashed.schedule(draft); await crashed.flush();
    answer = 0; assert.equal(await runAction('recover'), true);
    assert.equal(snapshot().path, null); assert.equal(snapshot().dirty, true);
    assert.match(snapshot().name, /Recovered/); assert.equal(snapshot().text, draft.text);
    nextSave = null; assert.equal(await runAction('save-as'), false);
    assert.ok((await protection.list()).records.length >= 1);
    nextSave = recoverySource; assert.equal(await runAction('save'), false);
    assert.match(errors.pop(), /different filename/);
    assert.equal(await fs.readFile(recoverySource, 'utf8'), recoveryBytes);
    nextSave = path.join(root, 'recovered-copy.fountain'); assert.equal(await runAction('save'), true);
    assert.equal(await fs.readFile(nextSave, 'utf8'), '\uFEFF' + draft.text.replaceAll('\n', '\r\n'));
    assert.equal((await protection.list()).records.some(item => item.record.id === draft.id), false);
    check('restart recovery stays unsaved, survives cancellation, protects source and preserves BOM/newlines');
    await edit('INT. BACKUP - DAY\n\nNew version.\n');
    const oldBytes = await fs.readFile(nextSave); assert.equal(await runAction('save'), true);
    const history = await protection.backups();
    const version = history.find(entry => entry.sourcePath === path.resolve(nextSave));
    assert.ok(version); assert.deepEqual(await fs.readFile(version.filePath), oldBytes);
    answer = 0; assert.equal(await runAction('backups'), true);
    assert.equal(snapshot().dirty, true); assert.equal(snapshot().path, null);
    assert.equal(snapshot().text, draft.text);
    nextSave = version.sourcePath; assert.equal(await runAction('save'), false);
    assert.match(errors.pop(), /different filename/);
    check('backups retain exact bytes and restore as protected unsaved copies');
    answer = 1; await runAction('new');
    const formatSource = 'INT. FORMAT ROOM - DAY\n\n!😀 **Bold** *italic* _underlined_ ***both*** [[secret]] /* omitted */\n\n@Jane\nHello.\nMore.\n\n@John ^\n(replying)\nYes.\n\n!<img src=x onerror=alert(1)>\n';
    await edit(formatSource);
    await waitFor("document.querySelector('.cm-content .inline-bold') && document.querySelector('.cm-content .inline-italic') && document.querySelector('.cm-content .inline-underline')", 'source emphasis marks');
    assert.equal(snapshot().text, formatSource);
    await js("document.getElementById('preview').click()");
    assert.equal(await js("document.getElementById('editor').hidden && !document.getElementById('preview-pane').hidden && document.getElementById('preview').getAttribute('aria-pressed') === 'true'"), true);
    assert.equal(await js("new Set(Array.from(document.querySelectorAll('#preview-content .dual-left,.dual-right')).map(row=>row.classList.contains('dual-left')?'left':'right')).size"), 2);
    assert.equal(await js("Array.from(document.querySelectorAll('#preview-content .dual-left')).map(row=>row.textContent.trim()).join('')"), 'JaneHello.More.');
    assert.equal(await js("Array.from(document.querySelectorAll('#preview-content .dual-right')).map(line=>line.textContent.trim()).join('')"), 'John(replying)Yes.');
    assert.equal(await js("getComputedStyle(document.querySelector('#preview-content .dual-left')).position"), 'absolute');
    assert.equal(await js("document.querySelectorAll('#preview-content img').length"), 0);
    const previewText = await js("document.getElementById('preview-content').textContent");
    assert.ok(previewText.includes('<img src=x onerror=alert(1)>'));
    assert.ok(!previewText.includes('secret') && !previewText.includes('omitted'));
    assert.ok(!previewText.includes('**') && !previewText.includes('@Jane'));
    assert.equal(snapshot().text, formatSource);
    check('live emphasis and simultaneous-dialogue preview preserve exact source and render markup safely');
    await remote('replace', { ...guard(), find: 'Hello.', replace: 'Good evening.', expectedOccurrences: 1 });
    await waitFor("Array.from(document.querySelectorAll('#preview-content .dual-left')).some(row=>row.textContent.includes('Good evening.'))", 'preview updates after automation');
    await js("document.getElementById('preview').click()");
    await remote('undo', guard()); assert.equal(snapshot().text, formatSource);
    await js("document.getElementById('preview').click()");
    await waitFor("document.querySelector('.outline-item.scene')?.textContent.includes('FORMAT ROOM')", 'current outline after undo');
    await js("document.querySelector('.outline-item.scene').click()");
    assert.equal(await js("document.getElementById('preview-pane').hidden && !document.getElementById('editor').hidden"), true);
    check('preview updates after guarded Codex edits; undo and outline navigation return to source editing');
    await js("document.getElementById('preview').click()");
    await fs.writeFile(path.join(root, 'desktop-preview.png'), (await win.capturePage()).toPNG());
    await js("document.getElementById('preview').click()");
    answer = 1; await runAction('new');
    await edit('Title: PDF Test\nAuthor: A Writer\n\nINT. PRINT ROOM - DAY\n\n!'+ 'An action sentence. '.repeat(450) + '\n\n@JANE\n'+ 'A dialogue sentence. '.repeat(240));
    await js("document.getElementById('preview').click()");
    const expectedPages = await js("document.querySelectorAll('#preview-content .screenplay-page').length");
    assert.ok(expectedPages >= 4);
    const beforeExport = snapshot(); nextSave = null;
    assert.equal(await runAction('export-pdf'), false);
    assert.equal(snapshot().dirty, true); assert.equal(snapshot().revision, beforeExport.revision);
    nextSave = path.join(root, 'screenplay-letter.pdf');
    assert.equal(await runAction('export-pdf'), true);
    const pdf = await fs.readFile(nextSave); assert.equal(pdf.subarray(0,5).toString(), '%PDF-');
    assert.equal(snapshot().text, beforeExport.text); assert.equal(snapshot().dirty, true);
    await fs.writeFile(path.join(root,'pdf-preview-pages.json'), JSON.stringify({expectedPages, size:'Letter'}));
    check('paginated Letter preview exports a real PDF without saving or changing the screenplay; cancellation preserves edits');
    await js("document.getElementById('paper-size').value='A4';document.getElementById('paper-size').dispatchEvent(new Event('change'))");
    assert.ok((await js("document.getElementById('preview-summary').textContent")).includes('A4'));
    nextSave = path.join(root, 'screenplay-a4.pdf'); assert.equal(await runAction('export-pdf'),true);
    await fs.writeFile(path.join(root,'desktop-pagination.png'), (await win.capturePage()).toPNG());
    check('A4 preview and PDF export use the selected physical page size');
    await js("document.getElementById('preview').click()");
    answer=1; await runAction('new');
    const writingSource='INT. ONE - DAY\n\n@JANE\nHello.\n\nEXT. TWO - NIGHT\n\n!Second.\n\n@JA';
    await edit(writingSource);
    await waitFor("!document.getElementById('character-suggestions').hidden && document.querySelector('#character-suggestions [role=option]').textContent==='JANE'",'character suggestion');
    win.webContents.sendInputEvent({type:'keyDown',keyCode:'TAB'});
    win.webContents.sendInputEvent({type:'keyUp',keyCode:'TAB'});
    await waitFor("window.beat.current().then(doc=>doc.text.endsWith('@JANE'))",'character accepted');
    assert.equal(snapshot().dirty,true);
    await remote('undo',guard()); assert.equal(snapshot().text,writingSource);
    await remote('redo',guard()); assert.ok(snapshot().text.endsWith('@JANE'));
    check('character suggestions accept known names and undo/redo as one protected editor transaction');
    await remote('select',{...guard(),from:0,to:0});
    await waitFor("!document.getElementById('scene-down').disabled",'scene move enabled');
    const beforeMove=snapshot().text;
    await js("document.getElementById('scene-down').click()");
    await waitFor("window.beat.current().then(doc=>doc.text.startsWith('EXT. TWO'))",'scene reorder');
    assert.ok(snapshot().text.includes('@JANE\nHello.'));
    assert.equal(snapshot().dirty,true);
    await remote('undo',guard()); assert.equal(snapshot().text,beforeMove);
    await remote('redo',guard()); assert.ok(snapshot().text.startsWith('EXT. TWO'));
    await js("document.getElementById('outline-filter').value='ONE';document.getElementById('outline-filter').dispatchEvent(new Event('input'))");
    assert.equal(await js("document.getElementById('scene-up').disabled && document.getElementById('scene-down').disabled"),true);
    await js("document.getElementById('outline-filter').value='';document.getElementById('outline-filter').dispatchEvent(new Event('input'))");
    check('outline scene moves preserve content, update selection, undo/redo together and disable while filtered');
    answer=1; await runAction('new');
    const fileMenu = require('electron').Menu.getApplicationMenu().items.find(item=>item.label==='File').submenu.items.map(item=>item.label);
    assert.ok(fileMenu.includes('Export Final Draft…') && fileMenu.includes('Recover unsaved screenplay…') && fileMenu.includes('Restore versioned backup…'));
    const fdxSource='INT. FDX ROOM - DAY #12A#\n\n!A **bold** action.\n\n@JANE\nHello.\n\n@JOHN ^\nReply.\n';
    await edit(fdxSource);
    nextSave=null; assert.equal(await runAction('export-fdx'),false); assert.equal(snapshot().text,fdxSource);
    nextSave=path.join(root,'screenplay.fdx'); assert.equal(await runAction('export-fdx'),true);
    const exportedFDX=await fs.readFile(nextSave,'utf8'); assert.ok(exportedFDX.includes('<FinalDraft') && exportedFDX.includes('<DualDialogue>'));
    assert.equal(snapshot().dirty,true); const importedSource=nextSave;
    answer=1; await runAction('new'); nextOpen=importedSource;
    assert.equal(await runAction('open'),true);
    await waitFor("document.getElementById('filename').textContent.includes('Imported')",'FDX import copy');
    assert.equal(snapshot().path,null); assert.equal(snapshot().dirty,true); assert.ok(snapshot().text.includes('#12A#'));
    nextSave=importedSource; assert.equal(await runAction('export-fdx'),false); assert.match(errors.pop(),/original source/);
    assert.equal(await fs.readFile(importedSource,'utf8'),exportedFDX);
    nextSave=path.join(root,'imported-copy.fountain'); assert.equal(await runAction('save'),true);
    assert.ok((await fs.readFile(nextSave,'utf8')).includes('@JOHN ^'));
    const malformed=path.join(root,'malformed.fdx');await fs.writeFile(malformed,'<FinalDraft><Content></FinalDraft>');nextOpen=malformed;
    const beforeBadImport=snapshot().id; assert.equal(await runAction('open'),false); assert.equal(snapshot().id,beforeBadImport); assert.ok(errors.pop());
    check('FDX export and unsaved-copy import preserve styles, scene numbers and dual dialogue; source overwrite and malformed import are blocked');
    answer=1; await runAction('new');
    await edit('INT. REVISIONS - DAY\n\nOriginal.\n');
    await js("document.getElementById('revision-track').click()");
    await waitFor("window.beat.current().then(doc=>doc.revisions.enabled)",'revision tracking enabled');
    const insertion=snapshot().text.length;
    await remote('edit',{...guard(),edits:[{from:insertion,to:insertion,expectedText:'',insert:'Added 😀 line.\n'}]});
    const tracked=snapshot().revisions;
    assert.deepEqual(tracked.ranges.map(r=>[r.from,r.to,r.kind]),[[insertion,insertion+15,'Addition']]);
    assert.equal(await js("!!document.querySelector('.revision-Addition')"),true);
    await remote('undo',guard()); assert.equal(snapshot().revisions.ranges.length,0);
    await remote('redo',guard()); assert.deepEqual(snapshot().revisions,tracked);
    check('tracked Codex additions show revision color and undo/redo restores text and marks together');
    await remote('select',{...guard(),from:insertion,to:insertion+5});
    await js("document.getElementById('revision-remove').click()");
    await waitFor("window.beat.current().then(doc=>doc.revisions.ranges.some(r=>r.kind==='RemovalSuggestion'))",'suggested removal');
    const removalText=snapshot().text, removalMarks=snapshot().revisions;
    assert.equal(removalText.includes('Added'),true);
    await remote('undo',guard()); assert.deepEqual(snapshot().revisions,tracked);
    await remote('redo',guard()); assert.deepEqual(snapshot().revisions,removalMarks);
    await protection.flush();
    const drafts=await protection.list();
    assert.deepEqual(drafts.records.find(entry=>entry.record.id===snapshot().id).record.revisions,removalMarks);
    assert.equal(await js("document.getElementById('scene-up').disabled && document.getElementById('scene-down').disabled"),true);
    check('suggested removals keep source text, undo independently and persist in recovery checkpoints');
    nextSave=path.join(root,'revision-tracking.fountain'); assert.equal(await runAction('save'),true);
    const revisionFile=await fs.readFile(nextSave,'utf8'); assert.ok(revisionFile.includes('"RemovalSuggestion":[['));
    answer=1; await runAction('new'); nextOpen=nextSave; assert.equal(await runAction('open'),true);
    await waitFor("document.getElementById('metadata-banner').hidden",'revision-only metadata remains editable');
    assert.equal(snapshot().readOnly,false); assert.deepEqual(snapshot().revisions,removalMarks); assert.equal(snapshot().text,removalText);
    await remote('edit',{...guard(),edits:[{from:0,to:0,expectedText:'',insert:'!Preface.\n\n'}]});
    assert.equal(snapshot().revisions.ranges.find(r=>r.kind==='RemovalSuggestion').from,insertion+11);
    assert.equal(await runAction('save'),true);
    await fs.writeFile(path.join(root,'desktop-revisions.png'),(await win.capturePage()).toPNG());
    check('native revision-only BEAT metadata reopens editable and range offsets follow subsequent edits');
    answer=1; await runAction('new');
    const taggedFile=path.join(root,'native-tagged.fountain');
    const nativeText='INT. TAGGED - DAY\n\n!A lamp glows.\n\nEXT. OTHER - NIGHT\n\n!Quiet.\n';
    const tagStart=nativeText.indexOf('lamp'), reviewStart=nativeText.indexOf('glows');
    const nativeOffset=pos=>nativeText.slice(0,pos).replaceAll('\n','\r\n').length;
    const nativeSettings={Tags:[{range:[nativeOffset(tagStart),4],type:'prop',definition:'lamp-id'}],TagDefinitions:[{id:'lamp-id',type:'prop',name:'Lamp'}],'Review Ranges':[{range:[nativeOffset(reviewStart),5],string:'Review <img src=x onerror=alert(1)> & 😀'}],'Caret Position':nativeOffset(tagStart),'Window Width':1100,'Page Size':0,'Active Plugins':[],'Heading UUIDs':[]};
    const taggedRaw='\uFEFF'+nativeText.replaceAll('\n','\r\n')+'/** settings: '+JSON.stringify(nativeSettings)+' **/\r\n';
    await fs.writeFile(taggedFile,taggedRaw); await openFile(taggedFile);
    await waitFor("document.querySelector('.native-tag') && document.querySelector('.native-review')",'native annotation decorations');
    assert.equal(snapshot().readOnly,false);assert.equal(snapshot().text,nativeText);
    assert.equal(await js("document.querySelectorAll('#editor img').length"),0);
    assert.equal(await js("window.beat.current().then(doc=>window.beat.update(doc.id,'!Unsafe.\\n'+doc.text,doc.revision+1))"),false);
    await remote('select',{...guard(),from:0,to:0});
    assert.equal(await js("document.getElementById('scene-down').disabled"),true);
    const originalNativeState=snapshot().revisions;
    await remote('edit',{...guard(),edits:[{from:0,to:0,expectedText:'',insert:'!Before.\n\n'}]});
    assert.equal(snapshot().revisions.annotations.tags[0].from,tagStart+10);
    assert.equal(snapshot().revisions.annotations.reviews[0].from,reviewStart+10);
    await remote('undo',guard());assert.deepEqual(snapshot().revisions,originalNativeState);
    await remote('redo',guard());
    check('modern native tags and reviews remain editable, render safely and follow guarded edits with undo/redo');
    const taggedPosition=snapshot().revisions.annotations.tags[0].from;
    await remote('edit',{...guard(),edits:[{from:taggedPosition,to:taggedPosition+4,expectedText:'lamp',insert:''}]});
    assert.equal(snapshot().revisions.annotations.tags.length,0);
    await remote('undo',guard());assert.equal(snapshot().revisions.annotations.tags.length,1);
    await protection.flush();
    const metadataDraft={id:randomUUID(),filePath:taggedFile,model:{original:taggedRaw},text:snapshot().text,revisions:snapshot().revisions,dirty:true,protectedPaths:new Set()};
    crashed.schedule(metadataDraft);await crashed.flush();
    answer=1;await runAction('new');answer=0;assert.equal(await runAction('recover'),true);
    await waitFor("document.querySelector('.native-tag') && document.getElementById('filename').textContent.includes('Recovered')",'native metadata recovery');
    assert.equal(snapshot().path,null);assert.equal(snapshot().dirty,true);assert.deepEqual(snapshot().revisions,metadataDraft.revisions);
    nextSave=taggedFile;assert.equal(await runAction('save'),false);assert.match(errors.pop(),/different filename/);
    assert.equal(await fs.readFile(taggedFile,'utf8'),taggedRaw);
    check('tag deletion undoes correctly and restart recovery retains native annotations while protecting the source');
    nextSave=path.join(root,'native-tagged-recovered.fountain');assert.equal(await runAction('save'),true);
    const recoveredNative=await fs.readFile(nextSave,'utf8');
    const nativeModel=require('../dist/document.cjs').decodeDocument(recoveredNative);
    assert.equal(nativeModel.bom,true);assert.equal(nativeModel.lineEnding,'\r\n');assert.equal(nativeModel.settingsFormat,'modern');
    assert.deepEqual(nativeModel.revisions,metadataDraft.revisions);assert.deepEqual(nativeModel.settings.TagDefinitions,nativeSettings.TagDefinitions);
    assert.equal(nativeModel.settings['Window Width'],1100);assert.equal(nativeModel.settings['Review Ranges'][0].string,nativeSettings['Review Ranges'][0].string);
    answer=1;await runAction('new');await openFile(nextSave);
    await waitFor("document.querySelector('.native-tag') && document.querySelector('.native-review')",'saved native annotations reopen');
    assert.equal(snapshot().readOnly,false);assert.deepEqual(snapshot().revisions,metadataDraft.revisions);
    await fs.writeFile(path.join(root,'desktop-native-metadata.png'),(await win.capturePage()).toPNG());
    check('native metadata saves preserve tag definitions, review comments, settings, BOM and CRLF and reopen editable');
    answer=1;await runAction('new');
    const uuidFile=path.join(root,'scene-uuids.fountain'), uuidOne='11111111-1111-4111-8111-111111111111',uuidTwo='22222222-2222-4222-8222-222222222222';
    const uuidText='INT. SAME - DAY\n\n!First.\n\nINT. SAME - DAY\n\n!Second.\n';
    const uuidRaw='\uFEFF'+uuidText.replaceAll('\n','\r\n')+'/** settings: '+JSON.stringify({'Heading UUIDs':[{string:'INT. SAME - DAY',uuid:uuidOne},{string:'INT. SAME - DAY',uuid:uuidTwo}]})+' **/';
    await fs.writeFile(uuidFile,uuidRaw);await openFile(uuidFile);
    await waitFor("document.getElementById('filename').textContent==='scene-uuids.fountain'",'native heading identities loaded');
    assert.equal(snapshot().readOnly,false);
    await remote('edit',{...guard(),edits:[{from:0,to:snapshot().revisions.headings[0].to,expectedText:'INT. SAME - DAY',insert:'EXT. RENAMED - NIGHT'}]});
    assert.equal(snapshot().revisions.headings[0].uuid,uuidOne);
    await remote('edit',{...guard(),edits:[{from:0,to:0,expectedText:'',insert:'INT. SAME - DAY\n\n!New.\n\n'}]});
    const uuidNew=snapshot().revisions.headings[0].uuid;assert.notEqual(uuidNew,uuidOne);assert.notEqual(uuidNew,uuidTwo);
    assert.deepEqual(snapshot().revisions.headings.slice(1).map(h=>h.uuid),[uuidOne,uuidTwo]);
    await remote('undo',guard());assert.deepEqual(snapshot().revisions.headings.map(h=>h.uuid),[uuidOne,uuidTwo]);
    await remote('redo',guard());assert.equal(snapshot().revisions.headings[0].uuid,uuidNew);
    const deletedFrom=snapshot().revisions.headings[1].from,deletedTo=snapshot().revisions.headings[2].from;
    await remote('edit',{...guard(),edits:[{from:deletedFrom,to:deletedTo,expectedText:snapshot().text.slice(deletedFrom,deletedTo),insert:''}]});
    assert.deepEqual(snapshot().revisions.headings.map(h=>h.uuid),[uuidNew,uuidTwo]);
    await remote('undo',guard());assert.deepEqual(snapshot().revisions.headings.map(h=>h.uuid),[uuidNew,uuidOne,uuidTwo]);
    check('scene UUIDs survive renames and duplicate headings; insertion/deletion undo and redo restore exact identities');
    const uuidDraft={id:randomUUID(),filePath:uuidFile,model:{original:uuidRaw},text:snapshot().text,revisions:snapshot().revisions,dirty:true,protectedPaths:new Set()};
    crashed.schedule(uuidDraft);await crashed.flush();answer=1;await runAction('new');answer=0;assert.equal(await runAction('recover'),true);
    await waitFor("document.getElementById('filename').textContent.includes('Recovered')",'scene identity recovery');
    assert.deepEqual(snapshot().revisions,uuidDraft.revisions);assert.equal(snapshot().dirty,true);
    nextSave=uuidFile;assert.equal(await runAction('save'),false);assert.match(errors.pop(),/different filename/);
    nextSave=path.join(root,'scene-uuids-recovered.fountain');assert.equal(await runAction('save'),true);
    const savedUuidModel=require('../dist/document.cjs').decodeDocument(await fs.readFile(nextSave,'utf8'));
    assert.equal(savedUuidModel.bom,true);assert.equal(savedUuidModel.lineEnding,'\r\n');assert.deepEqual(savedUuidModel.revisions,uuidDraft.revisions);
    answer=1;await runAction('new');await openFile(nextSave);await waitFor("document.getElementById('filename').textContent==='scene-uuids-recovered.fountain'",'saved UUID document reopened');
    assert.deepEqual(snapshot().revisions,uuidDraft.revisions);assert.equal(await fs.readFile(uuidFile,'utf8'),uuidRaw);
    check('scene UUID recovery protects the original and preserves identities through BOM/CRLF save and reopen');
    const bigFishFile=path.resolve('../Sample files/Big-Fish.fountain'),bigFishOriginal=await fs.readFile(bigFishFile,'utf8');
    await openFile(bigFishFile);await waitFor("document.querySelectorAll('.outline-item.scene').length>100",'editable Big Fish loaded');
    assert.equal(snapshot().readOnly,false);const fishIDs=snapshot().revisions.headings.map(h=>h.uuid);assert.equal(fishIDs.length,194);
    await remote('edit',{...guard(),edits:[{from:0,to:0,expectedText:'',insert:'!Windows UUID check.\n\n'}]});
    assert.deepEqual(snapshot().revisions.headings.map(h=>h.uuid),fishIDs);
    nextSave=path.join(root,'big-fish-uuid-copy.fountain');assert.equal(await runAction('save-as'),true);
    const savedFish=require('../dist/document.cjs').decodeDocument(await fs.readFile(nextSave,'utf8'));
    assert.deepEqual(savedFish.revisions.headings.map(h=>h.uuid),fishIDs);assert.equal(await fs.readFile(bigFishFile,'utf8'),bigFishOriginal);
    await fs.writeFile(path.join(root,'desktop-scene-uuids.png'),(await win.capturePage()).toPNG());
    check('Big Fish edits and saves as a separate copy with all 194 native heading UUIDs preserved');
    assert.deepEqual(errors, []);
    await fs.writeFile(path.join(root, 'results.json'), JSON.stringify({ version: '0.10.0', passed: checks.length, checks, errors }, null, 2));
    console.log(`DESKTOP TESTS PASSED: ${checks.length}`);
    await setConnection(false); app.exit(0);
  } catch (error) {
    console.error(error);
    const diagnostic = await js("({text:document.querySelector('.cm-content')?.textContent,outline:document.getElementById('outline')?.textContent,sceneCount:document.querySelectorAll('.outline-item.scene').length})").catch(() => null);
    await fs.writeFile(path.join(root, 'failure.png'), (await win.capturePage()).toPNG()).catch(() => {});
    await fs.writeFile(path.join(root, 'results.json'), JSON.stringify({ passed: checks.length, checks, errors, failure: error.stack, document: snapshot(), diagnostic }, null, 2));
    app.exit(1);
  }
};
