import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
const { version } = JSON.parse(await readFile('package.json','utf8'));
if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error('Invalid release version');
const folder = path.resolve(`release/${version}/Installer`), app = path.resolve(`release/${version}/BEAT Windows-win32-x64`);
await mkdir(folder,{recursive:true});
const payload = path.join(folder,'BEAT-Windows.zip');
const quote = value => "'" + value.replaceAll("'", "''") + "'";
const result = process.argv.includes('--existing-payload') ? { status: 0 } : spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',`$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.IO.Compression,System.IO.Compression.FileSystem; if (Test-Path -LiteralPath ${quote(payload)}) { Remove-Item -LiteralPath ${quote(payload)} }; [System.IO.Compression.ZipFile]::CreateFromDirectory(${quote(app)},${quote(payload)},[System.IO.Compression.CompressionLevel]::Optimal,$true)`],{stdio:'inherit',windowsHide:true});
if (result.status !== 0) throw new Error(`Installer payload creation failed: ${('error' in result ? result.error : result.status)}`);
const hash = createHash('sha256').update(await readFile(payload)).digest('hex').toUpperCase();
const source = (await readFile('scripts/installer.ps1','utf8')).replaceAll('@VERSION@',version).replaceAll('@HASH@',hash);
await writeFile(path.join(folder,'Install.ps1'),source);
await copyFile('scripts/uninstall.ps1',path.join(folder,'Uninstall.ps1'));
await writeFile(path.join(folder,'Install BEAT Windows.cmd'),'@echo off\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0Install.ps1"\r\nif errorlevel 1 (pause & exit /b 1)\r\npause\r\n');
await writeFile(path.join(folder,'SHA256SUMS.json'),JSON.stringify({version,unsigned:true,sha256:hash,file:'BEAT-Windows.zip'},null,2));
await writeFile(path.join(folder,'INSTALL.txt'),`BEAT Windows ${version} unsigned per-user installer\r\nKeep these files together and run Install BEAT Windows.cmd.\r\nInstalls in LocalAppData\\Programs\\BEAT Windows and adds a Start menu shortcut.\r\nNo administrator rights required. Updates retain old versions and user data.\r\nTo uninstall, close BEAT and run Uninstall.ps1 from the installed application directory.\r\nUser data is retained. This build is unsigned and has not been certified by Microsoft.\r\n`);
console.log(`Unsigned installer ready: ${folder}`);
